In [35]:
import pandas as pd
import numpy as np

In [36]:
df_COD = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_COD.csv')
df_FF = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_FF.csv')
df_PUBG = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_PUBG.csv')

In [37]:
df_COD

Username       waktu  \
0               Rezky kurnia  2023-06-21   
1              Nana Prasetya  2023-06-21   
2           Geraldo Wowiling  2023-06-21   
3                Liya Triana  2023-06-21   
4     Fendinata Rahman Hakim  2023-06-21   
...                      ...         ...   
4995         Pengguna Google  2019-09-30   
4996         Pengguna Google  2019-09-30   
4997         Pengguna Google  2019-09-30   
4998         Pengguna Google  2019-09-30   
4999         Pengguna Google  2019-09-30   

                                               Komentar  Rating  
0     terlalu sangat banyak update tidak jelas simpa...       1  
1     permainan salah satu game favorit saya game ny...       5  
2     gamenya sudah bagus sesungguh semua bagus kecu...       3  
3        mencari musuh tolong yang pintar kemampuan nya       2  
4     pilih tim sesuai skill bawah saya dan lawan se...       1  
...                                                 ...     ...  
4995  bagus ada beberapa masuk contoh damage nya kak...       4  
4996  good permainan tingkat kan lagi senjata lebih ...       4  
4997  orang bodoh yang asal rate kecil mereka tidak ...       5  
4998  untuk dari permainan garena sendiri sudah bagu...       5  
4999  kontrol kurang nyaman dengan sensitifitas terl...       3  

[5000 rows x 4 columns]

In [38]:
# Menggabungkan ketiga dataset dalam satu list
datasets = [df_COD, df_FF, df_PUBG]

# Proses untuk setiap dataset
for df in datasets:
    df["waktu"] = pd.to_datetime(df["waktu"])
    df["tahun"] = df["waktu"].dt.year
    df["bulan"] = df["waktu"].dt.month

## Mendefinisikan kolom Sentimen

In [67]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 4
threshold_negatif = 2
threshold_netral = 3

# Menerapkan analisis sentimen berdasarkan skor
df_COD['Sentimen'] = df_COD['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif' 
                                                                if x <= threshold_negatif else 'Netral')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_COD = df_COD[['tahun','bulan', 'Komentar','Rating', 'Sentimen']]

df_COD

tahun  bulan                                           Komentar  Rating  \
0      2023      6  terlalu sangat banyak update tidak jelas simpa...       1   
1      2023      6  permainan salah satu game favorit saya game ny...       5   
2      2023      6  gamenya sudah bagus sesungguh semua bagus kecu...       3   
3      2023      6     mencari musuh tolong yang pintar kemampuan nya       2   
4      2023      6  pilih tim sesuai skill bawah saya dan lawan se...       1   
...     ...    ...                                                ...     ...   
4995   2019      9  bagus ada beberapa masuk contoh damage nya kak...       4   
4996   2019      9  good permainan tingkat kan lagi senjata lebih ...       4   
4997   2019      9  orang bodoh yang asal rate kecil mereka tidak ...       5   
4998   2019      9  untuk dari permainan garena sendiri sudah bagu...       5   
4999   2019      9  kontrol kurang nyaman dengan sensitifitas terl...       3   

     Sentimen  
0     Negatif  
1     Positif  
2      Netral  
3     Negatif  
4     Negatif  
...       ...  
4995  Positif  
4996  Positif  
4997  Positif  
4998  Positif  
4999   Netral  

[5000 rows x 5 columns]

## Analisis sentimen berdasarkan rating yang diberikan 

In [41]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from jcopml.tuning import grid_search_params as gsp

## Data set Call of Duty

### Membagi dataset

In [42]:
X_COD = df_COD[['tahun','bulan','Rating']]
y_COD = df_COD.Sentimen

X_train, X_test, y_train, y_test = train_test_split(X_COD, y_COD, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4000, 3), (1000, 3), (4000,), (1000,))

## Model Random Forres

In [43]:
# Membuat Model
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# Memuat prediksi dari model
y_RFC_pred = model.predict(X_test)

# Menghitung akurasi model
accuracy = accuracy_score(y_test, y_RFC_pred)
print('Accuracy:', accuracy*100,"%")

Accuracy: 100.0 %


## Model KNN

In [44]:
# membuat model
Model_KNN = KNeighborsClassifier(n_neighbors=3)

#Melatih Model
Model_KNN.fit(X_train, y_train)

# Melakukan Uji pada data test
y_KNN_predict = Model_KNN.predict(X_test)

# Menhitung akurasi model
accuracy_KNN = accuracy_score(y_test, y_KNN_predict)
print('Accuracy:', accuracy_KNN*100, "%")

Accuracy: 99.9 %


## Model SVM

In [45]:
from sklearn.preprocessing import LabelEncoder

# Menggunakan LabelEncoder
le = LabelEncoder()
df_COD= df_COD.copy()
df_COD['Sentimen'] = le.fit_transform(df_COD['Sentimen'])


In [46]:
# membuat model
model_SVM = svm.SVC(kernel='linear')

#Melatih Model
model_SVM.fit(X_train, y_train)

#Memprediksi label untuk test set
y_pred = model_SVM.predict(X_test)

# Menghitung akurasi prediksi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy*100,'%')

Akurasi: 100.0 %


# Analisis Sentimen berdasarkan Komentar dari user

## 1. Dataset Free Fire

In [47]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 3
threshold_negatif = 2

# Menerapkan analisis sentimen berdasarkan skor
df_FF['Sentimen'] = df_FF['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_FF = df_FF[['tahun','bulan', 'Komentar','Rating', 'Sentimen']]

df_FF

tahun  bulan                                           Komentar  Rating  \
0      2023      6  tolong permainan ringan kan karena kasihan kam...       1   
1      2023      6  baca info permainan saja terus padahal sinyal ...       2   
2      2023      6  sudah update sinyal kenapa tidak stabil sih to...       2   
3      2023      6  update terus semua bug tidak urus jaringan saa...       5   
4      2023      6  tidak bisa berguna updet terus kita kalau main...       1   
...     ...    ...                                                ...     ...   
4995   2023      1  tolong baik tentang bug luar zona  hanya bisa ...       1   
4996   2023      1  untuk pihak garena free fire indonesiatolong b...       5   
4997   2023      1  jangan terlalu ada banyak alasan masalah pada ...       5   
4998   2023      1  saya mau kasih tahu buat garena free fire upda...       4   
4999   2023      1  akhir akhir saya sering rasa masalah macthing ...       5   

     Sentimen  
0     Negatif  
1     Negatif  
2     Negatif  
3     Positif  
4     Negatif  
...       ...  
4995  Negatif  
4996  Positif  
4997  Positif  
4998  Positif  
4999  Positif  

[5000 rows x 5 columns]

In [48]:
from imblearn.over_sampling import SMOTE
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score


## 1.1. Random Forres Classifier

#### Membagi data menggunakan metode Stratified K-Fold Cross Validation

In [49]:
# Load data
X = df_FF["Komentar"]
y = df_FF["Sentimen"]

# Membuat objek KFold dengan k=5
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [50]:
# Membuat objek vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer.fit_transform(X)

# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_resampled, y_resampled = sm.fit_resample(X_vect, y)

unique, counts = np.unique(y_resampled, return_counts=True)
print(list(zip(unique, counts)))

[('Negatif', 3074), ('Positif', 3074)]


In [51]:
# Melakukan Stratified K-Fold Cross Validation pada data
for fold, (train_index, test_index) in enumerate(kfold.split(X, y)):
    print(f"Fold {fold + 1}:")
    
    # Subset data pelatihan dan data pengujian
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Menghitung jumlah sentimen negatif dan positif pada subset pelatihan
    neg_count_train = np.sum(y_train == 'Negatif')
    pos_count_train = np.sum(y_train == 'Positif')
    
    # Menghitung jumlah sentimen negatif dan positif pada subset pengujian
    neg_count_test = np.sum(y_test == 'Negatif')
    pos_count_test = np.sum(y_test == 'Positif')
    
    print("Train Set:")
    print("Jumlah sentimen negatif:", neg_count_train)
    print("Jumlah sentimen positif:", pos_count_train)
    print("")
    
    print("Test Set:")
    print("Jumlah sentimen negatif:", neg_count_test)
    print("Jumlah sentimen positif:", pos_count_test)
    print("")


Fold 1:
Train Set:
Jumlah sentimen negatif: 2459
Jumlah sentimen positif: 1541

Test Set:
Jumlah sentimen negatif: 615
Jumlah sentimen positif: 385

Fold 2:
Train Set:
Jumlah sentimen negatif: 2459
Jumlah sentimen positif: 1541

Test Set:
Jumlah sentimen negatif: 615
Jumlah sentimen positif: 385

Fold 3:
Train Set:
Jumlah sentimen negatif: 2459
Jumlah sentimen positif: 1541

Test Set:
Jumlah sentimen negatif: 615
Jumlah sentimen positif: 385

Fold 4:
Train Set:
Jumlah sentimen negatif: 2459
Jumlah sentimen positif: 1541

Test Set:
Jumlah sentimen negatif: 615
Jumlah sentimen positif: 385

Fold 5:
Train Set:
Jumlah sentimen negatif: 2460
Jumlah sentimen positif: 1540

Test Set:
Jumlah sentimen negatif: 614
Jumlah sentimen positif: 386



In [52]:
# Membuat model RandomForestClassifier
model = RandomForestClassifier()

# Melakukan cross validation
scores = cross_val_score(model, X_resampled, y_resampled, cv=kfold)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")


Fold 1 Accuracy: 79.34959349593495 %
Fold 2 Accuracy: 79.02439024390245 %
Fold 3 Accuracy: 79.10569105691056 %
Fold 4 Accuracy: 79.49552481692433 %
Fold 5 Accuracy: 79.41415785191212 %


In [53]:
# Melatih model dengan data latih yang telah di-resampling
model.fit(X_resampled, y_resampled)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer.transform(X_test)
y_pred = model.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 100.00%
F1 Score: 100.00

Confusion Matrix:
 [[614   0]
 [  0 386]]


## 1.2 Model Naive Bayes

#### Membagi data menggunakan metode Leave-One-Out Cross Validation (LOOCV)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4000,), (1000,), (4000,), (1000,))

In [55]:
vect = TfidfVectorizer(max_features=1000, binary=True)
X_train_vect_ = vect.fit_transform(X_train)

sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_train_vect_, y_train)

unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))

[('Negatif', 2460), ('Positif', 2460)]


In [56]:
#Melihat kinerja model
nb = MultinomialNB()
nb.fit(X_train_res, y_train_res)
nb.score(X_train_res, y_train_res)

0.7951219512195122

In [57]:
X_test_vect = vect.transform(X_test)
y_pred = nb.predict(X_test_vect)

print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nCOnfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 71.90%
F1 Score: 72.17

COnfusion Matrix:
 [[447 167]
 [114 272]]


## 2. Membandingkan Akurasi score dari Analisis sentimen menggunakan model SVM pada Dataset COD dan PUBG 

In [58]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 4
threshold_negatif = 3

# Menerapkan analisis sentimen berdasarkan skor
df_COD['Sentimen'] = df_COD['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_COD = df_COD[['tahun','bulan', 'Komentar','Rating', 'Sentimen']]

# Menerapkan analisis sentimen berdasarkan skor
df_PUBG['Sentimen'] = df_PUBG['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_PUBG = df_PUBG[['tahun','bulan', 'Komentar','Rating', 'Sentimen']]

In [59]:
df_COD

tahun  bulan                                           Komentar  Rating  \
0      2023      6  terlalu sangat banyak update tidak jelas simpa...       1   
1      2023      6  permainan salah satu game favorit saya game ny...       5   
2      2023      6  gamenya sudah bagus sesungguh semua bagus kecu...       3   
3      2023      6     mencari musuh tolong yang pintar kemampuan nya       2   
4      2023      6  pilih tim sesuai skill bawah saya dan lawan se...       1   
...     ...    ...                                                ...     ...   
4995   2019      9  bagus ada beberapa masuk contoh damage nya kak...       4   
4996   2019      9  good permainan tingkat kan lagi senjata lebih ...       4   
4997   2019      9  orang bodoh yang asal rate kecil mereka tidak ...       5   
4998   2019      9  untuk dari permainan garena sendiri sudah bagu...       5   
4999   2019      9  kontrol kurang nyaman dengan sensitifitas terl...       3   

     Sentimen  
0     Negatif  
1     Positif  
2     Negatif  
3     Negatif  
4     Negatif  
...       ...  
4995  Positif  
4996  Positif  
4997  Positif  
4998  Positif  
4999  Negatif  

[5000 rows x 5 columns]

In [60]:
df_PUBG

tahun  bulan                                           Komentar  Rating  \
0      2023      6  saya sering saat loading in permainan kembali ...       2   
1      2023      6  bagus lah lama ini tapi peta livik masih harus...       4   
2      2023      6  mohon perhati karena saya bisa login lewat ema...       5   
3      2023      6  gamenya terlalu lama loadingnya buat tidak suk...       1   
4      2023      6  kirain sudah kasih ulasan permainan nya lebih ...       2   
...     ...    ...                                                ...     ...   
4995   2018      9  semakin lama permainan semakin kualitas hampir...       2   
4996   2018      9  banyak lag nya sudah update grafis sudah palin...       1   
4997   2018      9  kenapa sekarang suka dan sering keluar sendiri...       5   
4998   2018      9  pertama belum upgrade bagus sekarang sudah upg...       1   
4999   2018      9  payah update baru semakin sering ngelag patah ...       1   

     Sentimen  
0     Negatif  
1     Positif  
2     Positif  
3     Negatif  
4     Negatif  
...       ...  
4995  Negatif  
4996  Negatif  
4997  Positif  
4998  Negatif  
4999  Negatif  

[5000 rows x 5 columns]

## 2.1 Model SVM dataset COD

In [61]:
X = df_COD["Komentar"]  
y = df_COD["Sentimen"]  

# Membuat objek KFold dengan k=5
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [62]:
from sklearn.svm import SVC

# Inisialisasi vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer_PUBG = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer_PUBG.fit_transform(X_train)

# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_vect, y_train)

# Membuat model SVM
model_SVM = SVC(kernel='linear')

# Melakukan cross validation
scores = cross_val_score(model_SVM, X_train_res, y_train_res, cv=kfold)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")

Fold 1 Accuracy: 76.93089430894308 %
Fold 2 Accuracy: 77.33739837398373 %
Fold 3 Accuracy: 76.1178861788618 %
Fold 4 Accuracy: 74.79674796747967 %
Fold 5 Accuracy: 77.33739837398373 %


In [63]:
# Melatih model dengan data latih yang telah di-resampling
model_SVM.fit(X_train_res, y_train_res)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer_PUBG.transform(X_test)
y_pred = model_SVM.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 72.30%
F1 Score: 72.36

Confusion Matrix:
 [[471 143]
 [134 252]]


## 2.2 Model SVM dataset PUBG

In [64]:
from sklearn.model_selection import KFold

X = df_PUBG["Komentar"]  
y = df_PUBG["Sentimen"]  

# Membuat objek KFold dengan k=5
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [65]:
from sklearn.svm import SVC

# Inisialisasi vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer_PUBG = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer_PUBG.fit_transform(X_train)

# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_vect, y_train)

# Membuat model SVM
model_SVM = SVC(kernel='linear')

# Melakukan cross validation
scores = cross_val_score(model_SVM, X_train_res, y_train_res, cv=kfold)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")


Fold 1 Accuracy: 75.40650406504065 %
Fold 2 Accuracy: 75.60975609756098 %
Fold 3 Accuracy: 76.3211382113821 %
Fold 4 Accuracy: 74.39024390243902 %
Fold 5 Accuracy: 76.82926829268293 %


In [66]:
# Melatih model dengan data latih yang telah di-resampling
model_SVM.fit(X_train_res, y_train_res)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer_PUBG.transform(X_test)
y_pred = model_SVM.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 71.60%
F1 Score: 71.70

Confusion Matrix:
 [[464 150]
 [134 252]]
